/**
 * Domain type definitions for the TodoApp.
 *
 * ⚠️ IMPORTANT ARCHITECTURE CONSTRAINT:
 * This file contains ONLY TypeScript type and interface definitions.
 * Runtime constants (e.g. LocalStorage keys, magic strings, numeric limits)
 * must NOT be placed here. See src/lib/constants.ts for all runtime constants.
 *
 * Rationale (POA scope declaration, task-1779178940125):
 *   "型定義と定数定義の混在はプロダクトの長期メンテナビリティを損なうため承認しない"
 *   Mixing type definitions and runtime constants in the same file creates
 *   maintenance confusion and violates single-responsibility at the module level.
 */

// ---------------------------------------------------------------------------
// Core domain types
// ---------------------------------------------------------------------------

export type TodoStatus = "active" | "completed";

export type AnimationState = "idle" | "entering" | "exiting" | "transitioning";

export type SortBy = "date" | "due" | "status";

export type NotificationType = "success" | "error" | "info";

/**
 * The central domain entity representing a single todo item.
 */
export interface Todo {
  /** Unique identifier — timestamp-based UUID generated by TodoCore */
  id: string;
  /** User-supplied task title (1–100 characters) */
  title: string;
  /** Optional extended description */
  description?: string;
  /** Emoji used as visual category indicator (e.g. "💼", "🌸", "📚") */
  emoji: string;
  /** ISO 8601 date string for the optional due date */
  dueDate?: string;
  /** Whether the task has been completed */
  completed: boolean;
  /** ISO 8601 timestamp of when the todo was created */
  createdAt: string;
  /** ISO 8601 timestamp of when the todo was completed — undefined if still active */
  completedAt?: string;
  /** Soft-delete flag — true means the item is logically deleted but still in storage */
  deleted?: boolean;
}

// ---------------------------------------------------------------------------
// Filter & sort configuration
// ---------------------------------------------------------------------------

export type FilterStatus = "all" | "active" | "completed";

export interface FilterConfig {
  status: FilterStatus;
  emoji?: string;
  dueDateRange?: DueDateRange;
  searchQuery?: string;
}

export type DueDateRange = "today" | "tomorrow" | "overdue" | "this_week" | "all";

export interface CompleteFilterConfig extends FilterConfig {
  sortBy: SortBy;
}

// ---------------------------------------------------------------------------
// UI state types
// ---------------------------------------------------------------------------

export interface UiPreferences {
  /** Currently active theme variant identifier */
  themeVariant: string;
  /** Whether compact list mode is enabled */
  compactMode: boolean;
  /** Whether the sidebar/filter panel is open */
  sidebarOpen: boolean;
  /** Whether telemetry collection is disabled */
  telemetryOptOut: boolean;
}

export interface Notification {
  id: string;
  message: string;
  type: NotificationType;
  /** Unix timestamp (ms) after which the notification should auto-dismiss */
  expiresAt: number;
}

// ---------------------------------------------------------------------------
// Undo/redo types
// ---------------------------------------------------------------------------

export type UndoActionType = "delete" | "complete" | "update";

export interface UndoAction {
  type: UndoActionType;
  /** Snapshot of the todo state before the action was taken */
  previousState: Todo;
  /** Unix timestamp when the undo action was pushed */
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Storage stats type (returned by StorageAdapter)
// ---------------------------------------------------------------------------

export interface StorageStats {
  /** Estimated bytes used in LocalStorage */
  used: number;
  /** Estimated bytes remaining before quota is hit */
  available: number;
}
